import React, { useEffect } from 'react'
import Footer from '../components/Footer/Footer'
import Header from '../components/Header/Header'

function TermsAndConditions() {
    useEffect(() => {
        window.scrollTo(0, 0)
    }, [])
    return (
        <>
            <Header />
            <div className='privacyPolicyEmptyBox' />
            <div className='privayPolicyContainer'>
                <h1>Terms of Service</h1>
                <h2>Welcome! Thank you for your interest in TradeBuddy!</h2>
                <p>These Terms of Service (the “ToS”) applies with respect to the usage of the Platform (defined hereinafter) and the services offered by TradeBuddy and Nameless Technologies Pvt Ltd (“TradeBuddy”, “we”, or “us”), a TradeBuddy formed and incorporated under the Proprietorship Act, 2020 and having its registered office at D-008, GR Sankalpa, Banglore – 560098. Nameless Teams and Technologies conducts its business under the brand titled “TradeBuddy”, which is owned and operated by Nameless team and technologies. In these ToS, the term “TradeBuddy” shall mean Nameless Team and Technologies. These Terms of Service shall mutatis mutandis apply to mobile apps, WhatsApp groups, Facebook groups, Instagram pages, Facebook pages, email/SMS/phone communications and other communication forums/media hosted by Nameless Team and Technologies, which shall be deemed to be part of the Platform (defined hereinafter). Your usage of the TradeBuddy Services (defined hereinafter) is subject to your explicit acceptance of these ToS. The terms contained in our privacy policy available at (“PrivacyPolicy”), or any other policy of TradeBuddy related to the TradeBuddy Services are incorporated into these ToS by this reference. Your acceptance of the same will irrevocably and unconditionally bind you to comply with and abide by all the obligations and conditions stipulated herein (unless otherwise explicitly made optional). After your initial confirmation/consent, you will be assumed to continue consenting to these ToS until you explicitly withdraw your consent by notifying  Nameless Team and Technologies of the same in writing. If an executed agreement exists between You and  Nameless Team and Technologies in relation to the TradeBuddy Services, any deviations from these ToS shall only apply when explicitly agreed in writing between the parties to such an agreement. IF YOU DO NOT AGREE TO BE BOUND BY ALL CONDITIONS/CLAUSES CAPTURED IN THESE TOS, PLEASE DO NOT USE THE PLATFORM OR SERVICES.</p>
            </div>
            <div className='privacyPolicyBlueContainer'>
                <h2>Updation of Terms</h2>
                <p>These ToS may be updated, amended, modified or revised by us from time to time. Each such updation or modification to the ToS will be communicated to you via email, through the Website or any other medium. Your continued use of the TradeBuddy Services after any such changes shall constitute your consent to such changes. We encourage you to refer to these ToS from time to time to ensure that you are aware of any additions, revisions, amendments or modifications that we may have made.</p>
                <p>Service(s) provided to Users</p>
                <p>TradeBuddy allows its users to access various training programs on computer sciences designed by TradeBuddy for undergraduates and professionals, including TradeBuddy Edge, TradeBuddy Academy, TradeBuddy Plus or any other program or application that TradeBuddy introduces from time to time (hereinafter collectively referred to as “Service(s)” or “TradeBuddy Service(s)” and each of these training programs shall be referred to as a “Program” and collectively as “Programs”). TradeBuddy reserves the right, in its sole discretion, to add, change, suspend, or discontinue all or any part of the TradeBuddy Services at any time. Your continued use of TradeBuddy Services following the posting of any changes to the same (including the addition or removal of features) constitutes your acceptance of those changes. Any information you provide to us for the purposes of registering and setting up your account (as specified below) shall be considered as accurate, complete and updated. You are solely responsible for the activity that occurs on your account (including those of others authorised to access and operate your account) and for maintaining the security of your account and any information you input. We are not responsible for the accuracy or legitimacy of any information, data, or User Data uploaded or posted on the Platform. For the purposes of clarity, as long as your account is accessed with the correct login credentials and unless you notify us of any unauthorised access, you shall be solely responsible for all actions/defaults related to your account.</p>
                <p>In consideration of your acceptance of these ToS and if applicable, any subscription agreement (or any other similar agreement) executed between you and TradeBuddy, TradeBuddy grants the User a personal, non-exclusive, non-transferable, non-sublicensable, revocable limited license to access and use the Platform and Services, in accordance with the ToS.</p>
            </div>
            <div className='privayPolicyContainer'>
                <h2>Registration and Account Integrity</h2>
                <p>As part of the registration process, you will need to accept our ToS, and also provide us with your name, your phone number, your email ID and in certain scenarios, contact information of your parents/guardian. We would not at any time request you to provide us with access to your password, unless you have given us explicit written permission to access your account pursuant to a request for assistance or support.</p>
                <p>It is your responsibility to ensure that the information you provide is accurate, secure, and not misleading. You cannot create an account username and password using (i) the names and information of another person; or (ii) using words that are the trademarks or the property of another party (including ours); or (iii) words that are vulgar, obscene or in any other way inappropriate. You agree and confirm that you will never use another User’s account nor provide access to your account to any third-party. You agree and acknowledge that you are solely responsible for the activities that occur on your account, and you shall keep your account password secure and not share the same with anyone. You must notify TradeBuddy immediately of any breach of security or unauthorized use of your account. At no point in time will TradeBuddy be liable for any losses caused by any unauthorized use of your account, and you shall solely be liable for the losses caused to TradeBuddy or others due to such unauthorized use, if any.</p>
                <p>You shall be solely responsible for obtaining and maintaining any equipment or ancillary services necessary to connect to, access, receive the TradeBuddy Services or use the Platform, including, without limitation, hardware devices, software, and other internet, wireless, broadband, phone or other mobile communication device connection services. You shall be solely responsible for ensuring that such equipment or ancillary services are compatible with the Platform, and you shall be responsible for all charges incurred in connection with the use of the Platform or TradeBuddy Services in connection with all such equipment and ancillary services.</p>
            </div>
            <div className='privacyPolicyBlueContainer'>
                <h2>Use of your Information and User Data</h2>
                <p>All User Data that you create, transmit, transfer to us, submit, display or otherwise make available while using the TradeBuddy Services, should only be information that you own or have the right to use or share (as may be applicable). If you transfer any personally identifiable information to us, we will assume that you have informed the person concerned and procured the necessary consent for such transfer, sharing, processing and/or using the information on the Platform and/or in respect of the Services. We may use the above information as per our Privacy Policy and in accordance with applicable laws.</p>
                <p>While we make commercially reasonable efforts to ensure that the data stored on our servers is persistent and always available to our Users, we will not be responsible in the event of failure of the third-party servers or any other factors outside our reasonable control, that may cause the User Data to be permanently deleted, irretrievable, or temporarily inaccessible.</p>
            </div>
            <div className='privayPolicyContainer'>
                <h2>Third Party Links and Services</h2>
                <p>We use multiple third-party service providers in order to power and provide you with the TradeBuddy Services. In this process, we share the User Data with some of the third-party service providers, as is necessary to enable them to provide the requisite services. We will attempt to ensure that all our third-party service providers are bound by and adhere to the same obligations of confidentiality and data privacy as we guarantee to you. The Platform may include links to any third-party websites. TradeBuddy has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third-party website. By using the Platform, you expressly release TradeBuddy from any liability arising from your use of any third-party website or services.</p>
            </div>
            <div className='privacyPolicyBlueContainer'>
                <h2>Rules and Acceptable Usage Policy</h2>
                <p>As a condition of use, you promise not to use the TradeBuddy Services for any purpose that is prohibited by these ToS, by law, or other rules or policies implemented by us from time to time. The TradeBuddy Services and TradeBuddy Content is provided only for your own personal, non-commercial use. You agree to notify us immediately in case you observe any other User breaching the terms contained herein or any policy associated with the Programs.</p>
                <p>While using the Platform, you shall not:</p>
                <p>harass any third party including any Users or Customers;create an atmosphere of disharmony, hostility within student groups; use unethical methods during any assignment, test/exam conducted on the Platform or otherwise in relation to any Program; share any TradeBuddy Content (including any study materials or test materials) with anybody through any media; share solutions to assignments/test materials pertaining to the Platform. Furthermore, you shall not (directly or indirectly): (i) take any action that imposes or may impose an unreasonable or disproportionately large load on TradeBuddy’s (or its third party providers’) infrastructure; (ii) interfere or attempt to interfere with the proper working of the Platform; (iii) bypass any measures we may use to prevent or restrict access to the TradeBuddy Services (or parts thereof); (iv) modify, translate, or otherwise create derivative works of any part of the TradeBuddy Services or the Platform; or (v) copy, rent, download, extract, lease, distribute, or transfer any part of the Platform, TradeBuddy Content or any third party User Data, unless TradeBuddy specifically allows you to do so.</p>
            </div>
            <div className='privayPolicyContainer'>
                <h2>Content Ownership and Copyright Conditions of Access</h2>
                <p>The Platform and the TradeBuddy Content, including but not limited to all text, graphics, user interfaces, visual interfaces, sounds, artwork and computer code are owned and controlled by TradeBuddy and/or its licensors and the design, structure, selection, expression and arrangement of such content mentioned hereinabove is protected by copyright, patent and trademark laws, and other applicable laws on intellectual property rights. We reserve all rights, title, and ownership in and to the Platform and TradeBuddy Content.</p>
                <p>TradeBuddy’s logos, trademarks and service marks that may appear on the Platform, including but not limited to “TradeBuddy”, “TradeBuddy TradeBuddy”, “TradeBuddy Edge”, “TradeBuddy Academy” and “TradeBuddy Plus” (collectively, “TradeBuddy Marks”) are the property of TradeBuddy and are protected under applicable laws on intellectual property rights.</p>
                <p>Your copying, distributing, displaying, reproducing, modifying, or in any other way using of the TradeBuddy Content in any manner not specified in these ToS, will be a violation of copyright and other intellectual property rights and TradeBuddy reserves its rights under applicable law accordingly.</p>
                <p>You shall, at all times, remain the complete owner and retain all rights and title in and to the User Data. This includes assuming liability and responsibility in cases where the User Data breaches any conditions of confidentiality, any intellectual property rights, or any other third-party rights. By posting any User Data through the TradeBuddy Services, you grant TradeBuddy and its affiliates, a worldwide, non-exclusive, royalty-free, irrevocable, sub-licensable and transferable license to use, copy, reformat, modify, translate, display, sell, create derivative works and distribute such User Data for or in connection with the use of the TradeBuddy Services.</p>
            </div>
            <div className='privacyPolicyBlueContainer'>
                <h2>Reviews and Feedback</h2>
                <p>You agree that we may contact you through telephone, email, SMS, or any other electronic means of communication for the purpose of:</p>
                <p>Obtaining feedback in relation to the Platform or TradeBuddy Services; and/or Resolving any complaints, information, or queries received from you regarding the same. Any feedback provided by you may be used by TradeBuddy without any restriction or obligation to compensate you, and we are under no obligation to keep such feedback confidential.</p>
            </div>
            <div className='privayPolicyContainer'>
                <h2>Rights and Obligations relating to the Content</h2>
                <p>You are prohibited from:</p>
                <ul>
                    <li>violating or attempting to violate the integrity or security of the Platform or any content therein;transmitting any information (including messages and hyperlinks) on or through the Platform that is disruptive or competitive to the provision of our Services;</li>
                    <li>distributing in any medium, any part of the Platform or the TradeBuddy Content without TradeBuddy’s prior written authorisation;</li>
                    <li>reproducing, duplicating, copying, selling, reselling or exploiting for any commercial purpose any TradeBuddy Content or any portion thereof, other than as expressly allowed under this ToS;</li>
                    <li>using the TradeBuddy Marks in connection with, or to transmit, any unsolicited communications or emails or for any other unauthorised purpose;</li>
                    <li>intentionally submitting on the Platform any incomplete, false or inaccurate information;</li>
                    <li>using any engine, software, tool, agent or other device or mechanism (such as spiders, robots etc.) to navigate or search the Platform;</li>
                    <li>attempting to decipher, decompile, disassemble, alter, modify or reverse engineer any part of the Platform;</li>
                    <li>copying or duplicating in any manner any of the TradeBuddy Content or other information available from the Platform;</li>
                    <li>posting or transmitting, or cause to be posted or transmitted, any communication or solicitation or other “phishing”, “pharming” or “whaling” message designed or intended to obtain password, account, personal information, or confidential information from any other User or any other third party whatsoever;</li>
                    <li>using or launching any automated system, including without limitation, “robots,” “spiders,” or “offline readers,” that accesses the Platform in a manner that sends more request messages to TradeBuddy’s servers in a given period of time than a human can reasonably produce in the same period by using a conventional on-line web browser;</li>
                    <li>circumventing or disabling any digital rights management, usage rules, or other security features of the Platform; or</li>
                    <li>allowing any third party to access the Platform through your account unless TradeBuddy specifically allows you to do so.</li>
                    <li>You shall not host, display, upload, modify, publish, transmit, update or share any information/content that:</li>
                    <li>belongs to another person and to which the User does not have any right;</li>
                    <li>is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libellous, invasive of another’s privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful or inappropriate in any manner whatsoever;</li>
                    <li>harm minors in any manner;</li>
                    <li>infringes any patent, trademark, copyright or other proprietary rights;</li>
                    <li>violates any law for the time being in force;</li>
                    <li>deceives or misleads the addressee about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;</li>
                    <li>impersonates another person;</li>
                    <li>contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource;</li>
                </ul>
                <p>threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognisable offence or prevents investigation of any offence or is insulting any other nation. You understand that while using the Platform, you may be exposed to User Data pertaining to other Users, and that TradeBuddy is not responsible for such User Data. You further understand and acknowledge that you may be exposed to User Data that is inaccurate, offensive, indecent, or objectionable, and you agree to waive, and hereby do waive, any legal or equitable rights or remedies you have or may have against TradeBuddy in relation thereto.</p>
                <p>TradeBuddy shall, upon obtaining knowledge by itself or been brought to actual knowledge in writing or through email about any breach of the above conditions, may temporarily suspend/delete your account, impose penalties, or take any other actions that TradeBuddy may deem fit. We shall also be entitled to preserve such information and produce such records before governmental and/or judicial and/or regulatory authorities for investigation purposes as may be required by applicable law.</p>
                <p>In your use of the Platform, you will at all times comply with all applicable laws and regulations. In case of non-compliance with any applicable laws, rules or regulations, or this ToS by a User, we shall have the right to immediately terminate your access or usage rights to the Platform and to remove non-compliant User Data from the Platform. TradeBuddy shall not be liable to refund any fees/consideration collected from a Customer in case such Customer’s access to the Platform is terminated by TradeBuddy for any reason detailed herein.</p>
                <p>In the course of your usage of the TradeBuddy Services, you may post reviews, comments, suggestions, ideas, questions and other content, or send any other communications as long as the content is not illegal, obscene, threatening, defamatory, invasive of privacy, infringing any third party’s intellectual property rights, or otherwise injurious to third parties or objectionable and does not consist of or contain software viruses, political campaigning, commercial solicitation, chain letters, mass mailings or any other form of spam. Further, you hereby grant TradeBuddy a limited, royalty-free, worldwide, non-exclusive license to use the User Data (including the contents specified herein) in further developing the Platform and for the purpose of its marketing or promotional activities.</p>
            </div>
            <div className='privacyPolicyBlueContainer'>
                <h2>Support</h2>
                <p>TradeBuddy offers online support tools. You may access support resources or contact our support team by emailing us at connect@tradebuddy.io. TradeBuddy shall use commercially reasonable efforts to respond to your request for support, or to fix any problems you may be having, as is applicable. Any suggestions by TradeBuddy to you regarding use of the Platform shall not be construed as a warranty.</p>
            </div>
            <div className='privayPolicyContainer'>
                <h2>Termination</h2>
                <p>TradeBuddy reserves the right to suspend or terminate your access to the Platform and the services with or without notice and to exercise any other remedy available under law, in cases where:</p>
                <p>you are in breach of any terms and conditions of this ToS;</p>
                <p>TradeBuddy is unable to verify or authenticate any information provided to TradeBuddy by you; or TradeBuddy has reasonable grounds for suspecting any illegal, fraudulent or abusive activity on your part.</p>
                <p>Once temporarily suspended, indefinitely suspended or terminated, you may not continue to use the Platform under the same account, a different account or re-register under a new account. TradeBuddy may destroy and/or delete all the data and other information related to your account as per its discretion. All provisions of the ToS, which by their nature should survive termination, shall survive termination, including without limitation, warranty disclaimers, indemnity and limitations of liability.</p>
            </div>
            <div className='privacyPolicyBlueContainer'>
                <h2>Disclaimer</h2>
                <p>THE SCALER SERVICES AND THE SCALER CONTENT ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS AND ARE WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, AND ANY WARRANTIES IMPLIED BY ANY COURSE OF PERFORMANCE OR USAGE OF TRADE, ALL OF WHICH ARE EXPRESSLY DISCLAIMED. INTERVIEWBIT AND ITS DIRECTORS, EMPLOYEES, AGENTS, SUPPLIERS, SPONSORS AND PARTNERS DO NOT WARRANT THAT: (A) THE SCALER SERVICES AND THE PLATFORM WILL BE SECURE, ERROR-FREE OR AVAILABLE AT ANY PARTICULAR TIME OR LOCATION; (B) ANY DEFECTS OR ERRORS WILL BE CORRECTED; (C) ANY CONTENT OR SOFTWARE AVAILABLE AT OR THROUGH THE PLATFORM IS FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS; OR (D) THE RESULTS OF USING THE PLATFORM WILL MEET YOUR REQUIREMENTS. THE SCALER SERVICES MAY BE SUBJECT TO LIMITATIONS, DELAYS, AND OTHER PROBLEMS INHERENT IN THE USE OF THE INTERNET AND ELECTRONIC COMMUNICATIONS. INTERVIEWBIT IS NOT RESPONSIBLE FOR ANY DELAYS, DELIVERY FAILURES, OR OTHER DAMAGE RESULTING FROM SUCH PROBLEMS. YOUR USE OF THE PLATFORM AND THE SCALER SERVICES IS SOLELY AT YOUR OWN RISK.</p>
                <p>You will be awarded a certificate of successful completion of a Program (“Program Certificate”) upon fulfilling the criteria and requirements of TradeBuddy, which TradeBuddy may update from time to time. The decision to award any such Program Certificate or other acknowledgement of successful completion of a Program, would be solely at TradeBuddy’s discretion. TradeBuddy may choose not to offer any such Program Certificate or other acknowledgement of successful completion, for some Programs. TradeBuddy may decide at its sole discretion whether to provide a record concerning a Customer’s performance in a Program. The format of any certificate, credential or other acknowledgement, and of any performance, provided by TradeBuddy relating to a Program will be determined by TradeBuddy at its sole discretion and may vary as per the Program.</p>
                <p>TradeBuddy has no obligation to have the TradeBuddy Services, TradeBuddy Content, Programs or Program Certificates recognized by or affiliated to any educational institution or accreditation organization. TradeBuddy provides education related services through the Platform. The Platform or the TradeBuddy Services MUST NOT be construed as a university. The Users understand and acknowledge that TradeBuddy cannot award certificates which are recognised by any regulatory body such as the All India Council for Technical Education or University Grants Commission.</p>
                <p>It is the sole responsibility of the Customer enrolling into a Program to check the accuracy of, and evaluate the suitability and relevance of, the Program elected. The enrolment into a Program is non-transferable.</p>
                <p>You acknowledge that certain parts of the Platform may be enabled by third-party service providers, and you agree to abide by their terms and conditions to the extent such terms are applicable to you. TradeBuddy shall not be responsible for any disruption of TradeBuddy Services caused by any such third-party service provider.</p>
            </div>
            <div className='privayPolicyContainer'>
                <h2>Indemnification</h2>
                <p>You shall defend, indemnify, and hold harmless TradeBuddy, its affiliates, subsidiaries and each of its, and its affiliates’ and subsidiaries’ employees, contractors, directors, suppliers and representatives from all liabilities, losses, claims, and expenses, including reasonable attorneys’ fees, that arise from or relate to (i) your use or misuse of, or access to, the Platform and/or TradeBuddy Services; (ii) your violation of the ToS or any applicable law; (iii) your violation of any rights of a third party in relation to the usage of the Platform. We reserve the right to assume the exclusive defence and control of any matter otherwise subject to indemnification by you, in which event you will assist and cooperate with us in connection therewith.</p>
            </div>
            <div className='privacyPolicyBlueContainer'>
                <h2>Limitation of Liability</h2>
                <p>TO THE FULLEST EXTENT PERMITTED BY LAW, IN NO EVENT SHALL INTERVIEWBIT (NOR ITS DIRECTORS, EMPLOYEES, AGENTS, SPONSORS, PARTNERS, SUPPLIERS, CONTENT PROVIDERS, LICENSORS OR RESELLERS,) BE LIABLE UNDER CONTRACT, TORT, STRICT LIABILITY, NEGLIGENCE OR ANY OTHER LEGAL OR EQUITABLE THEORY WITH RESPECT TO THE SERVICE (I) FOR ANY LOST PROFITS, DATA LOSS, LOSS OF GOODWILL OR OPPORTUNITY, OR SPECIAL, INDIRECT, INCIDENTAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES OF ANY KIND WHATSOEVER; OR (II) FOR YOUR RELIANCE ON THE SCALER SERVICES; OR (III) FOR ANY DIRECT DAMAGES IN EXCESS (IN THE AGGREGATE) OF ONE THOUSAND RUPEES (INR 1,000/-); OR (IV) FOR ANY MATTER BEYOND ITS REASONABLE CONTROL, EVEN IF INTERVIEWBIT HAS BEEN ADVISED OF THE POSSIBILITY OF ANY OF THE AFOREMENTIONED DAMAGES.</p>
            </div>
            <div className='privayPolicyContainer'>
                <h2>Governing Law</h2>
                <p>The ToS shall be governed by and construed in accordance with the laws of India without regard to the conflict of laws provisions thereof. All claims, differences and disputes arising under or in connection with or in relation hereto the Platform, the ToS or any transactions entered into on or through the Platform shall be subject to the exclusive jurisdiction of the courts at Bengaluru, India and you hereby accede to and accept the jurisdiction of such courts.</p>
            </div>
            <div className='privacyPolicyBlueContainer'>
                <h2>Payments</h2>
                <p>Unless otherwise expressly agreed in writing by TradeBuddy, full payment for enrolment and participation in a Program is required at the time of registration. To make payment for any Program or to purchase any services or products offered by TradeBuddy through the Platform, you must have internet access and a current valid accepted payment method as indicated on the Platform (“Payment Method”). TradeBuddy does not store any of your credit card information or such other information restricted by the Reserve Bank of India (RBI) for processing payment and has partnered with payment gateways for the payment towards the services. By using a third-party payment provider, you agree to abide by the terms/policies of such third-party payment provider. You agree that in case TradeBuddy’s third-party payment provider stores any such information, TradeBuddy will not be responsible for such storage, and it will be solely at your discretion to allow the third party to store such information as per its terms/policies. TradeBuddy shall in no way be liable for loss of such information or any loss incurred by you due to the misuse of such information and TradeBuddy shall not be obligated to reimburse you for any such loss or to hold you harmless in any manner. You also agree to pay all applicable fees for the payments made through the Platform.</p>
                <p>TradeBuddy does not support all payment methods, currencies or locations for payment. All applicable taxes are calculated based on the billing information you provide to us at the time of enrolment/purchase. Your transactions on the Platform may be subject to foreign exchange fees or exchange rates.</p>
            </div>
            <div className='privayPolicyContainer'>
                <h2>Refund Policy</h2>
                <p>A Customer may opt out of certain Programs subscribed by him/her and seek a refund for the fees already paid in relation thereto, provided the Customer informs us in writing regarding the same and seeks the refund prior to the expiry of the Refund Window (as detailed in the table below). The Refund Window is calculated from the date of the first className/session of the relevant Program subscribed by the Customer. We shall not entertain any requests related to refund of fees after the expiry of the Refund Window. IT MUST BE NOTED, THAT NOTWITHSTANDING THE MODE OF PAYMENT USED FOR PAYING THE FEES, THE REFUND SHALL ALWAYS BE MADE TO A BANK ACCOUNT (AS PER THE DETAILS PROVIDED BY THE CUSTOMER) THROUGH NEFT/IMPS/RTGS OR SUCH OTHER FACILITY AS DEEMED FIT BY UPSYK. WE MAY REQUEST FOR INFORMATION/DOCUMENTS (WHICH MAY INCLUDE A CANCELLED CHEQUE PERTAINING TO THE BANK ACCOUNT OF THE CUSTOMER) TO VERIFY YOUR CREDENTIALS AND DETAILS OF THE BANK ACCOUNT BEFORE INITIATING THE REFUND. WE SHALL STRIVE TO PROCESS THE REFUNDS WITHIN THIRTY (30) DAYS OF RECEIPT OF ALL THE RELEVANT INFORMATION AND DOCUMENTATION FROM YOU IN THIS REGARD. We do not provide refunds for the lack of usage, dissatisfaction with the Program or for any reason whatsoever after the expiry of the Refund Window.</p>

            </div>
            <div className='privacyPolicyBlueContainer'>
                <h2>Pause Feature</h2>
                <p>Our Programs’ pace and workload can be varied by Customers as per their needs. We have enabled a “Pause” feature through which a User enrolled in the Program titled “TradeBuddy Crash Course” (or any other Program as may be determined by TradeBuddy) may temporarily pause or suspend his/her engagement with the Program. A Customer may opt to pause a Program for up to four (4) weeks twice every year at no additional costs. During the period in which a Program is “paused”, the relevant Customer shall not be allowed to access the Program or any TradeBuddy Content related thereto through the Platform. If a User opts to pause a Program beyond the two (2) pauses that he/she is entitled to, each such pause shall be chargeable at an amount determined by TradeBuddy in its sole discretion and such amount may be updated from time to time, exclusive of applicable taxes, and shall be subject to TradeBuddy’s specific approval. As of now, the amount chargeable by TradeBuddy for such additional pauses is INR 4,999/-.</p>
            </div>
            <div className='privayPolicyContainer'>
                <h2>Policy for NDNC</h2>
                <p>By using the Website and/or registering yourself at tradebuddy.io you authorise us to contact you via email or phone call or sms and offer you our services, imparting product knowledge, offer promotional offers running on website & offers offered by the associated third parties, for which reasons, personally identifiable information may be collected. And irrespective of the fact if also you have registered yourself under DND or DNC or NCPR service, you still authorise us to give you a call from TradeBuddy Academy for the above mentioned purposes till 365 days of your registration with us. This Privacy Policy covers TradeBuddy Academy's treatment of personally identifiable information that TradeBuddy Academy collects when you are on the TradeBuddy Academy's site, and when you use TradeBuddy Academy's services. This policy also covers TradeBuddy Academy's treatment of personally identifiable information that TradeBuddy Academy's business partner shares with TradeBuddy Academy. This policy does not apply to the certain TradeBuddy Academy's products or services, when you visit TradeBuddy Academy's pages, and when you enter promotions. TradeBuddy Academy may also receive personally identifiable information from our business partners. When you registered with TradeBuddy Academy, we ask for your first name, last name, contact no, email, Date of Birth and gender. Once you register with TradeBuddy Academy and sign in to our services, you are not anonymous to us. Also during registration, you may be requested to register your mobile phone and email id, pager, or other device to receive text messages, and other services to your wireless device. By registration you authorise us to send sms/email alerts to you for your login details and any other service requirements or some advertising messages/emails from us.</p>
            </div>
            <div className='privacyPolicyBlueContainer'>
                <h2>Copyright Infringement Notice</h2>
                <p>If a User believes in good faith that his/her copyright has been infringed, the User may provide us with a written communication which contains:</p>
                <p>An electronic or physical signature of the person authorized to act on behalf of the owner of the copyright interest/work;</p>
                <p>A description of the copyrighted work that the User claims has been infringed upon; A description of where the material that the User claims is infringing is located on the Platform, and any other details identifying the infringing material;</p>
                <p>The User’s email address, address and telephone number;</p>
                <p>A statement by the User affirming that the User has a good faith belief that the disputed use is not authorized by the copyright owner, his/her agent, or the law; and</p>
                <p>A statement by the User, made under penalty of perjury, that the information in the copyright notice is accurate and that the User is the copyright owner or authorized to act on behalf of the copyright owner.The Copyright infringement notice needs to be sent to the following address:</p>
                <p>Attention: Ashish Kumar</p>
                <p>D-008, GR Sankalpa,</p>
                <p>Hosa Road, Bangalore 560099</p>
                <p>Email: connect@tradebuddy.io</p>
            </div>
            <div className='privayPolicyContainer'>
                <h2>Miscellaneous</h2>
                <p>If any provision of the ToS is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary so that the ToS will otherwise remain in full force and effect and enforceable.</p>
                <p>Any failure by TradeBuddy to enforce any right or failure to act with respect to any breach by you under the ToS shall not be construed as, or constitute, a continuing waiver of such provision, or a waiver of any other breach of or failure to comply with any other provision of the ToS, unless any such waiver has been consented to by us in writing.</p>
                <p>These ToS is personal to you and is not assignable or transferable by you except with TradeBuddy’s prior written consent. TradeBuddy may assign, transfer or delegate any of its rights and obligations hereunder without your consent.</p>
                <p>No agency, partnership, joint venture, or employment relationship is created as a result of the ToS and neither party has any authority of any kind to bind the other in any respect in relation to any third party.</p>
                <p>All notices under the ToS will be in writing and will be deemed to have been duly given when received, if personally delivered or sent by certified or registered mail, return receipt requested; when receipt is electronically confirmed, if transmitted by facsimile or e-mail; or two days after it is sent, if sent for next day delivery by recognized overnight delivery service.</p>
                <p>TradeBuddy shall not be liable for failure to perform, or the delay in performance of, any of its obligations if, and to the extent that, such failure or delay is caused by events substantially beyond its control, including but not limited to acts of God, acts of the public enemy or governmental body in its sovereign or contractual capacity, war, terrorism, floods, fire, strikes, pandemics, epidemics, civil unrest or riots, power outage, and/or unusually severe weather.</p>
                <p>By accepting the ToS through your use of the Platform, you certify and acknowledge that you are 18 years of age or older. If you are under the age of 18 or under the legal age in your jurisdiction to enter into a binding contract, you must use the Platform only under the supervision of a parent or legal guardian who agrees to be bound by the ToS. If you are a parent or legal guardian agreeing to this ToS for the benefit of an individual below 18 year of age, please be advised that you are fully responsible for his/her use of the Platform, including all financial charges and legal liability that he/she may incur. By using the Platform, you represent and warrant that you have the right, authority, and capacity to enter into this ToS and to abide by all of the terms and conditions set forth herein.</p>
                <p>Terms and Conditions for Evangelist Program</p>
                {/* There is a link tag */}
                <p>Click here to know more about the Terms and Conditions for Evangelist Program</p>
            </div>
            <div className='privacyPolicyBlueContainer'>
                <h2>Contact Us</h2>
                {/* <p>In the event you have any queries/complaints regarding usage of the Platform, including but not limited to reporting any violation of these Terms of Service, please contact our Grievance Officer, Saurabh Saxena at saurabh@TradeBuddy.com. The complaints will be redressed in the manner provided under the Information Technology Act, 2000 and rules framed thereunder.</p> */}
                <p>In the event you have any queries/complaints regarding usage of the Platform, including but not limited to reporting any violation of these Terms of Service, please contact our Grievance Officer, Saurabh Saxena at connect@tradebuddy.io. The complaints will be redressed in the manner provided under the Information Technology Act, 2000 and rules framed thereunder.</p>
                <p>Definitions</p>
                <p>The following defined terms having their respective meanings as provided below have been used in these ToS:</p>
                <p>“Customer” refers to any User who has paid and subscribed to any of the Programs, which may include execution of a subscription agreement (or any similar agreement executed between such User and TradeBuddy) or compliance with certain additional terms by the User in this regard; “Platform” shall mean the websites www.tradebuddy.io and www.tradebuddy.io (collectively, the “Website”), and any other platform (including chat groups, TradeBuddy hosted social media forums/pages and webpages) which may allow you to access and/or use the TradeBuddy Services via any other device/medium; “TradeBuddy Content” means and includes all questionnaires, interview ideas, study/course material in any format, ideas, concepts, inventions, systems, platforms, software, interfaces, tools, utilities, templates, forms, techniques, design formats, methods, processes, algorithms, know-how, trade secrets, and other technologies and information acquired, created, developed or licensed independently by us, prior to or outside the scope of these ToS and any improvement, modification, extension or other derivative works thereof and all intellectual property rights thereto. TradeBuddy Content excludes all User Data; “User Data” means all electronic data, information, or other content submitted or provided by a User to be stored, collected or processed by us in connection with such User’s authorised use of the TradeBuddy Services; “ You ” or “ User ” shall mean any user of the Platform.</p>
                <p>These Terms of Service constitute an 'electronic record' within the meaning of the applicable law (including the Information Technology Act, 2000) and is generated by a computer system and does not require any physical or digital signatures.</p>
            </div>
            <div className='privacyPolicyEmptyBox' />
            <Footer />
        </>
    )
}

export default TermsAndConditions
